leandrodasler/checkout-b2b

- CHANGELOG.md
- package.json
- react/CheckoutB2B.tsx
- react/utils/index.tsx
Show the shipping address to the user when they checkout.
Just put `checkout-b2b` in your theme.
[Workspace](https://icaroov--bravtexfashionb2b.myvtex.com)
> feat: Adiciona o endereço selecionado nos totalizadores [868a19ckx]

- messages/en.json
- messages/es.json
- messages/pt.json
- react/utils/index.tsx
- react/utils/messages.ts
Adding the reference_sku column to the table to store unique SKU references for products.
> feat: add reference_sku column to table

- CHANGELOG.md
- messages/en.json
- messages/es.json
- messages/pt.json
- react/CheckoutB2B.tsx
- react/package.json
- react/utils/index.tsx
- react/utils/messages.ts
- store/blocks/store.checkout-b2b.jsonc
- store/interfaces.json
Show the brand product and go back to home button.
Just put `checkout-b2b` in your theme.
[Workspace](https://icaroov--bravtexfashionb2b.myvtex.com)
> feat: adds new column and back to home button

- messages/en.json
- messages/es.json
- messages/pt.json
- react/utils/index.tsx
- react/utils/messages.ts
Includes totalPrice in the table schema for better visibility of total prices.
> feat: include totalPrice in table

- manifest.json
- package.json
- react/CheckoutB2B.tsx
- react/package.json
- react/yarn.lock
- store/blocks/store.checkout-b2b.jsonc
> feat: using css handles; post-merge hook

- manifest.json
- messages/en.json
- messages/es.json
- messages/pt.json
- package.json
- react/CheckoutB2B.tsx
- react/hooks/useOrderFormCustom.ts
- react/package.json
- react/utils/messages.ts
- react/yarn.lock
> feat: clear cart button

- messages/en.json
- messages/es.json
- messages/pt.json
- react/utils/index.tsx
- react/utils/messages.ts
Added the seller column to the table for better seller identification.
> feat: add seller column to the table

- messages/en.json
- messages/es.json
- messages/pt.json
- react/CheckoutB2B.tsx
- react/utils/index.tsx
- react/utils/messages.ts
Adding payment method options to the checkout process for better user experience.
> feat: add payment methods options to checkout

- CHANGELOG.md
- react/CheckoutB2B.tsx
- react/hooks/useOrderFormCustom.ts
- react/hooks/useToolbar.ts
Implements search by SKU name or reference code to cart items
Just put `checkout-b2b` in your theme.
[Workspace](https://icaroov--bravtexfashionb2b.myvtex.com)
> [CU-868abwz5y] Implementa busca por nome do SKU ou código de referência aos itens do carrinho

- docs/README.md
> docs: update README with new information

- react/hooks/usePlaceOrder.ts
Change order redirect to use full page reload
> Change order redirect to use full page reload

- messages/en.json
- messages/es.json
- messages/pt.json
- react/CheckoutB2B.tsx
- react/components/ProductAutocomplete.tsx
- react/hooks/useAddItems.ts
- react/hooks/useToolbar.ts
- react/utils/index.ts
- react/utils/messages.ts
Keep search autocomplete options open when selecting items to add to cart.
> feat: do not close search autocomplete on add item to cart

- messages/en.json
- messages/es.json
- messages/pt.json
- react/CheckoutB2B.tsx
- react/components/ProductAutocomplete.tsx
- react/graphql/getProducts.graphql
- react/utils/index.ts
- react/utils/messages.ts
Show both individual SKUs and grouped product options
[Workspace](https://workspacedev--bravtexfashionb2b.myvtex.com/checkout-b2b)
> feat: grouped product autocomplete

- messages/en.json
- messages/es.json
- messages/pt.json
- react/CheckoutB2B.tsx
- react/CheckoutB2BContext.tsx
- react/utils/messages.ts
> refactor:  toggling search store

- react/components/ProductAutocomplete.tsx
- react/hooks/useDebounce.ts
> feat: debounce add to cart function

- .github/workflows/publish-and-deploy.yml
> ci: using publish and deploy action v2

- .devcontainer/devcontainer.json
…
[Workspace](Link goes here!)
> chore: create devcontainer.json for use github codespace with installed vtex-cli

- react/components/ProductAutocomplete.tsx
[Workspace](https://teste--bravtexfashionb2b.myvtex.com/checkout-b2b)
> Remove itens

- react/components/SavedCartTable.tsx
apply saved cart delivery option
[Workspace](https://teste--bravtexfashionb2b.myvtex.com/checkout-b2b)
> feature: apply-saved-cart-delivery-option

- messages/en.json
- messages/es.json
- messages/pt.json
- react/components/ContactInfos.tsx
- react/components/ManualPrice.tsx
- react/components/RepresentativeBalanceData.tsx
- react/graphql/getRepresentativeBalanceByEmail.graphql
- react/hooks/useFetchRepresentativeBalance.ts
- react/hooks/useManualPrice.ts
- react/utils/messages.ts
This PR improves the user experience and functionality related to the "Representative Incentive Balance" feature during Checkout.
Specifically, it includes:
- Displaying a label in the buyer’s data section showing:
- The current balance of the sales representative.
- The projected change (credit or debit) based on the current order manual prices.
- Adding visual indicators (↑/↓) in the checkout product table for items with price changes:
- If the manual price increases → indicates **credit** to the rep's balance.
- If the manual price decreases → indicates **debit** from the rep's balance.
- Creating two custom hooks:
- One to handle logic related to `manualPrice` and compute the difference.
- One to correctly fetch and manage the representative balance data.
This helps both the …
> feat: representative balance checkout view

- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/CheckoutB2B.tsx
- react/hooks/useTableSchema.tsx
- react/utils/messages.ts
Agora tem a possibilidade de selecionar e deletar múltiplos itens de uma só vez
Na tela de checkout adicione itens e selecione a lixeira caso queira deletar. Workspace: joaomarcosworkspace
[Workspace](https://joaomarcosworkspace--bravtexfashionb2b.myvtex.com)
> feat: delete multiple items checkout

- react/CheckoutB2B.tsx
- react/CheckoutB2BContext.tsx
- react/hooks/usePermissions.ts
[Workspace](https://joaomarcosworkspace--bravtexfashionb2b.myvtex.com/checkout-b2b)
No visual changes
> fix: change max discount to use sales admins only
